import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "@/component/layout/Navbar/Navbar";
import Footer from "@/component/layout/Footer/Footer";
import 'swiper/css';
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Provider from "@/component/shared/providers/provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",

  icons: {
    icon: [
      { url: "freshcart-logo.49f1b44d.svg", type: "image/svg+xml" },
    ],
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>

      </head>
      <body className="min-h-full flex flex-col">

        <main>
          <Provider>
            <Navbar />
            {children}
            <Toaster position="top-right" className="text-black" />
            <Footer />
          </Provider>
        </main>


      </body>
    </html>
  );
}
